apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-12-gitops
  description: This is GitOps manifest for python-12   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: python-12
    janus-idp.io/tekton: python-12 
    backstage.io/kubernetes-id: python-12 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:python-12
